// Automatically generated by Lily Deep-Research Engine at Mon, 31 Aug 2026 11:46:17 GMT
// Auto-syncs every 30 minutes in GitHub Cloud

window.HACKATHONS_DATA = [
  {
    "id": "devnovate-2026",
    "title": "DevNovate 2026 National Innovation Hackathon",
    "organizer": "DevNovate Foundation & Devfolio",
    "logo": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80",
    "bannerGradient": "from-indigo-600 via-purple-700 to-slate-950",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "Devfolio Virtual & Bangalore Hub",
    "totalPrizePool": 500000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "DevNovate",
      "Devfolio",
      "AI/ML",
      "FinTech",
      "HealthTech",
      "Web3"
    ],
    "shortTeaser": "Flagship national innovation hackathon bringing together 5,000+ developers to build transformative AI agents, next-gen decentralized finance, and public health software.",
    "timelines": {
      "registrationDeadline": "2026-09-08T11:46:17.562Z",
      "revealDate": "2026-08-27T11:46:17.562Z",
      "submissionDeadline": "2026-09-06T23:46:17.562Z",
      "winnerAnnouncement": "2026-09-16T11:46:17.562Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Developers",
        "Designers",
        "Students",
        "Founders"
      ],
      "teamSizeMin": 2,
      "teamSizeMax": 4,
      "geography": "Open to All Developers Globally & India",
      "studentOnly": false,
      "prerequisites": "Must register on DevNovate portal with public GitHub profile."
    },
    "tracks": [
      {
        "id": "devnovate-track-ai",
        "title": "Track 1: Agentic AI & Autonomous Developer Tooling",
        "prize": "₹2,00,000 Cash + Cloud Infrastructure Grants",
        "problemStatement": "Build autonomous multi-agent pipelines that understand codebase repositories, automate bug fixes, and generate verified test suites with zero hallucination.",
        "keyRequirements": [
          "Integrate LLM tool calling (Gemini, Claude, or OpenAI)",
          "Provide real-time execution sandboxing (WebAssembly or Docker)",
          "Demonstrate automated git commit & PR creation"
        ],
        "evaluationCriteria": "35% Autonomous Accuracy, 30% Architecture & Speed, 20% UI/UX, 15% Pitch Demo"
      },
      {
        "id": "devnovate-track-fintech",
        "title": "Track 2: Next-Gen Open Banking & Fraud Prevention",
        "prize": "₹1,50,000 Cash + Incubator Fast-Track",
        "problemStatement": "Design a real-time transactional anomaly detection engine capable of scoring synthetic identity fraud and payment laundering across 5,000 TPS.",
        "keyRequirements": [
          "Sub-50ms inference latency for transaction risk scoring",
          "Explainable AI feature attribution dashboard",
          "Compliance with PCI-DSS & Open Banking API specs"
        ],
        "evaluationCriteria": "40% Anomaly Detection Precision, 30% System Throughput, 30% Usability"
      },
      {
        "id": "devnovate-track-health",
        "title": "Track 3: Decentralized Health Records & Diagnostic AI",
        "prize": "₹1,50,000 Cash + Venture Mentorship",
        "problemStatement": "Create a privacy-preserving medical imaging analysis tool that runs local federated learning models on edge devices without exposing raw patient health data.",
        "keyRequirements": [
          "Client-side WebGPU or ONNX model inference",
          "Zero-knowledge proof verification for patient access logs",
          "FHIR standard medical data interoperability"
        ],
        "evaluationCriteria": "40% Privacy Architecture, 30% Clinical Utility, 30% Prototype Quality"
      }
    ],
    "judges": [
      {
        "name": "Saurabh Sharma",
        "role": "VP of Engineering, DevNovate & Cloud Architect",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Distributed systems, agentic workflow orchestration, and low-latency API design."
      },
      {
        "name": "Dr. Ananya Ray",
        "role": "Head of AI Research & Venture Partner",
        "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Algorithmic soundness, dataset integrity, and market commercialization."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with MIT/Apache license and comprehensive README documentation",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "All submitted code and models must be developed within the hackathon timeline."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Next.js 15 (App Router) + FastAPI (Python) + PostgreSQL / Pinecone + Vercel Deployment",
      "proTips": [
        "Include a clear 1-minute video showing the agent executing end-to-end without cuts.",
        "Add benchmark performance charts in your submission pitch deck to stand out to judges."
      ]
    },
    "registrationUrl": "https://devfolio.co/hackathons",
    "submissionUrl": "https://devfolio.co"
  },
  {
    "id": "unstop-amazon-hackon-6",
    "title": "HackOn with Amazon 6.0",
    "organizer": "Amazon & Unstop",
    "logo": "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/user-images/6571520626359_amazon.svg",
    "bannerGradient": "from-amber-600 via-orange-700 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "Unstop Virtual & India",
    "totalPrizePool": 225000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "Unstop",
      "Amazon",
      "Software Dev",
      "PPI Opportunities",
      "Engineering"
    ],
    "shortTeaser": "Amazon's flagship student hackathon on Unstop. Solve real e-commerce, cloud, and AI engineering challenges for cash prizes & Pre-Placement Interviews (PPIs).",
    "timelines": {
      "registrationDeadline": "2026-09-10T11:46:17.563Z",
      "revealDate": "2026-08-26T11:46:17.563Z",
      "submissionDeadline": "2026-09-09T05:46:17.563Z",
      "winnerAnnouncement": "2026-09-20T11:46:17.563Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "B.Tech/B.E.",
        "M.Tech",
        "MCA Students"
      ],
      "teamSizeMin": 2,
      "teamSizeMax": 4,
      "geography": "India & South Asia Engineering Students",
      "studentOnly": true,
      "prerequisites": "Must register through Unstop platform."
    },
    "tracks": [
      {
        "id": "amazon-track-1",
        "title": "Track 1: High-Scale E-Commerce & AI Customer Experience",
        "prize": "₹2,25,000 + Amazon Pre-Placement Interviews (PPI)",
        "problemStatement": "Architect a resilient, fault-tolerant microservice that predicts inventory demand spikes and handles 100,000 requests/sec during festive sales.",
        "keyRequirements": [
          "Use Java, Python, or Go for core backend logic",
          "Include architectural system design diagram",
          "Demonstrate load testing results"
        ],
        "evaluationCriteria": "40% System Scalability, 30% Code Architecture, 30% Prototype Demo"
      }
    ],
    "judges": [
      {
        "name": "Amazon Tech Leaders",
        "role": "Principal Software Engineers, Amazon",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Distributed systems, low latency, and operational excellence."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with system architecture documentation",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Authored specifically for HackOn with Amazon 6.0."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Java Spring Boot / Python FastAPI + AWS DynamoDB + Docker + React",
      "proTips": [
        "Include load testing benchmarks (JMeter / K6) in your submission deck to impress Amazon judges."
      ]
    },
    "registrationUrl": "https://unstop.com/hackathons/hackon-with-amazon-60-amazon-1150000",
    "submissionUrl": "https://unstop.com"
  },
  {
    "id": "unstop-iitg-innovatex",
    "title": "IIT Guwahati Pitch & Build InnovateX 2026",
    "organizer": "IIT Guwahati & Unstop",
    "logo": "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/branding/unstop-logo.png",
    "bannerGradient": "from-emerald-800 via-teal-900 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "IIT Guwahati Campus & Unstop",
    "totalPrizePool": 10000000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "Unstop",
      "IIT Guwahati",
      "DeepTech",
      "₹1 Crore Pool",
      "Startup Grants"
    ],
    "shortTeaser": "Massive pan-India DeepTech & AI pitchathon hosted by IIT Guwahati on Unstop with ₹1 Crore (~$120,000 USD) in cash rewards & incubation grants.",
    "timelines": {
      "registrationDeadline": "2026-09-14T11:46:17.563Z",
      "revealDate": "2026-08-21T11:46:17.563Z",
      "submissionDeadline": "2026-09-13T07:46:17.563Z",
      "winnerAnnouncement": "2026-09-25T11:46:17.563Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Students",
        "Research Scholars",
        "Early Startups"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 5,
      "geography": "Global & India",
      "studentOnly": false,
      "prerequisites": "Working functional prototype required for round 2."
    },
    "tracks": [
      {
        "id": "iitg-track-1",
        "title": "Track 1: AI, Robotics & Sustainable Hardware Innovation",
        "prize": "₹1 Crore Total Fund Pool & IIT Incubation",
        "problemStatement": "Develop hardware or software solutions addressing clean energy, agricultural automation, or medical robotics.",
        "keyRequirements": [
          "Functional MVP demo",
          "10-slide pitch deck"
        ],
        "evaluationCriteria": "40% Market Potential, 30% Technical Feasibility, 30% Prototype Quality"
      }
    ],
    "judges": [
      {
        "name": "IITG Incubation Board",
        "role": "Professors & Venture Partners",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Commercial viability and IP patent potential."
      }
    ],
    "rules": {
      "repoRequirement": "GitHub repo or hardware CAD / code archive",
      "demoVideoMaxSecs": 240,
      "liveUrlRequired": false,
      "slideDeckRequired": true,
      "codeFreshness": "Original startup project or prototype."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Python PyTorch / ROS2 + React + Embedded Microcontrollers",
      "proTips": [
        "Highlight unit economics and patent applications in your deck."
      ]
    },
    "registrationUrl": "https://unstop.com/hackathons",
    "submissionUrl": "https://unstop.com"
  },
  {
    "id": "google-ai-2026",
    "title": "Google AI Hackathon 2026",
    "organizer": "Google DeepMind & Google Cloud",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    "bannerGradient": "from-blue-600 via-indigo-700 to-purple-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "Global Virtual",
    "totalPrizePool": 100000,
    "currency": "$",
    "featured": true,
    "tags": [
      "AI/ML",
      "Gemini 2.0",
      "Google Cloud",
      "Multimodal",
      "Open to All"
    ],
    "shortTeaser": "Build next-gen autonomous multimodal AI agents and developer tools using Gemini 1.5/2.0 Pro & Flash APIs.",
    "timelines": {
      "registrationDeadline": "2026-09-07T11:46:17.563Z",
      "revealDate": "2026-08-21T11:46:17.563Z",
      "submissionDeadline": "2026-09-05T23:46:17.563Z",
      "winnerAnnouncement": "2026-09-18T11:46:17.563Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Students",
        "Professionals",
        "Researchers",
        "Indie Hackers"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "geography": "Global (excluding sanctioned regions)",
      "studentOnly": false,
      "prerequisites": "Must use Google AI Studio API or Google Cloud Vertex AI."
    },
    "tracks": [
      {
        "id": "google-track-1",
        "title": "Track 1: Multimodal AI Agents for High-Impact Workflows",
        "prize": "$40,000 + $10k Cloud Credits",
        "problemStatement": "Design an end-to-end autonomous agent capable of processing unstructured video, audio, code, and document streams simultaneously to solve healthcare, legal, logistics, or scientific research problems.",
        "keyRequirements": [
          "Process at least 2 distinct modal inputs (e.g., Video + PDF text)",
          "Implement function calling with Gemini 1.5 Pro or Flash",
          "Provide structured JSON responses or dynamic UI output"
        ],
        "evaluationCriteria": "35% Technical Innovation, 25% Real-World Utility, 20% UI/UX Design, 20% Pitch & Demo Quality"
      }
    ],
    "judges": [
      {
        "name": "Demis Hassabis",
        "role": "CEO, Google DeepMind",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Scientific breakthroughs, algorithmic elegance, and multi-step agent reasoning."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with Apache 2.0 or MIT license",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "All core code must be created during the official hackathon window."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Next.js 15 (App Router) + Tailwind CSS + Google AI Studio SDK + Vercel Deployment",
      "proTips": [
        "Record a crisp 2-minute video pitch highlighting the exact problem statement within the first 15 seconds."
      ]
    },
    "registrationUrl": "https://googleai.devpost.com",
    "submissionUrl": "https://googleai.devpost.com/submit"
  },
  {
    "id": "microsoft-imagine-cup-2026",
    "title": "Microsoft Imagine Cup 2026",
    "organizer": "Microsoft",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    "bannerGradient": "from-sky-700 via-blue-800 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "Global Online & Seattle Finals",
    "totalPrizePool": 100000,
    "currency": "$",
    "featured": true,
    "tags": [
      "Microsoft",
      "Azure AI",
      "Student Founder",
      "$100k Prize",
      "Global"
    ],
    "shortTeaser": "The premier global student technology competition. Build an AI-driven startup on Microsoft Azure for $100,000 USD, mentorship from Satya Nadella, and global recognition.",
    "timelines": {
      "registrationDeadline": "2026-09-20T11:46:17.563Z",
      "revealDate": "2026-08-16T11:46:17.563Z",
      "submissionDeadline": "2026-09-16T01:46:17.563Z",
      "winnerAnnouncement": "2026-10-15T11:46:17.563Z"
    },
    "eligibility": {
      "minAge": 16,
      "allowedRoles": [
        "Students (High School, Undergrad, Grad)"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "geography": "Worldwide",
      "studentOnly": true,
      "prerequisites": "Must utilize Microsoft Azure AI or OpenAI on Azure."
    },
    "tracks": [
      {
        "id": "imagine-track-1",
        "title": "Track 1: AI-Powered Global Impact Ventures",
        "prize": "$100,000 USD + Mentorship with Satya Nadella",
        "problemStatement": "Build an MVP leveraging Azure OpenAI, Computer Vision, or Speech services to address accessibility, sustainability, education, or healthcare inequities.",
        "keyRequirements": [
          "Working proof-of-concept deployed on Azure",
          "3-minute pitch video explaining commercial viability",
          "Architecture system documentation"
        ],
        "evaluationCriteria": "30% Innovation & AI Integration, 25% Business Model, 25% User Experience, 20% Pitch Quality"
      }
    ],
    "judges": [
      {
        "name": "Microsoft Executive Panel",
        "role": "Microsoft Corporate VPs & Fellows",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Scalability, ethics in AI, and global market potential."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with architecture diagram",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Authored for Imagine Cup 2026 cycle."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Azure Container Apps + Next.js + Azure OpenAI GPT-4o + CosmosDB",
      "proTips": [
        "Emphasize how your solution can turn into a venture-backed startup."
      ]
    },
    "registrationUrl": "https://imaginecup.microsoft.com",
    "submissionUrl": "https://imaginecup.microsoft.com"
  },
  {
    "id": "dorahacks-weex-ai-wars",
    "title": "DoraHacks WEEX AI Wars II",
    "organizer": "WEEX & DoraHacks",
    "logo": "https://dorahacks.io/favicon.ico",
    "bannerGradient": "from-amber-500 via-orange-600 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "DoraHacks Global Virtual",
    "totalPrizePool": 200000,
    "currency": "$",
    "featured": true,
    "tags": [
      "DoraHacks",
      "AI Agents",
      "Trading Algos",
      "Web3",
      "Grant Pool"
    ],
    "shortTeaser": "Global AI and algorithmic intelligence hackathon on DoraHacks. Build autonomous trading models, risk sentinels, and LLM financial copilots.",
    "timelines": {
      "registrationDeadline": "2026-09-12T11:46:17.563Z",
      "revealDate": "2026-08-23T11:46:17.563Z",
      "submissionDeadline": "2026-09-10T03:46:17.563Z",
      "winnerAnnouncement": "2026-09-22T11:46:17.563Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Quant Developers",
        "AI Researchers",
        "Web3 Builders"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 5,
      "geography": "Global",
      "studentOnly": false,
      "prerequisites": "Must submit on DoraHacks BUIDL portal."
    },
    "tracks": [
      {
        "id": "dorahacks-track-1",
        "title": "Track 1: Autonomous High-Frequency AI Agents & Market Sentinel",
        "prize": "$80,000 USD BUIDL Grant Pool",
        "problemStatement": "Train an LLM or Reinforcement Learning agent capable of analyzing live orderbook depth, sentiment news streams, and executing volatility arbitrage safely.",
        "keyRequirements": [
          "Backtesting performance logs",
          "Open-source strategy repo",
          "Live demo dashboard"
        ],
        "evaluationCriteria": "40% Backtesting Sharpe Ratio, 30% Code Modularity, 30% Real-Time Inference"
      }
    ],
    "judges": [
      {
        "name": "Eric Zhang",
        "role": "Founder, DoraHacks",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Public goods innovation, decentralized governance, and algorithmic resilience."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with open MIT license",
      "demoVideoMaxSecs": 150,
      "liveUrlRequired": true,
      "slideDeckRequired": false,
      "codeFreshness": "Created during hackathon."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Python PyTorch / Ray + Rust Execution Engine + Next.js UI",
      "proTips": [
        "Include stress-test scenario simulations (e.g. flash crash handling)."
      ]
    },
    "registrationUrl": "https://dorahacks.io/hackathon",
    "submissionUrl": "https://dorahacks.io"
  },
  {
    "id": "solana-renaissance-2026",
    "title": "Solana Renaissance Global Hackathon",
    "organizer": "Solana Foundation & Colosseum",
    "logo": "https://solana.com/favicon.ico",
    "bannerGradient": "from-fuchsia-600 via-purple-700 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "Global Virtual",
    "totalPrizePool": 1000000,
    "currency": "$",
    "featured": true,
    "tags": [
      "Solana",
      "Web3",
      "DeFi",
      "DePIN",
      "Consumer Apps",
      "$1M Prize"
    ],
    "shortTeaser": "The premier Solana ecosystem hackathon with $1,000,000 in prizes and pre-seed investment into Colosseum's accelerator program.",
    "timelines": {
      "registrationDeadline": "2026-09-06T11:46:17.563Z",
      "revealDate": "2026-08-17T11:46:17.563Z",
      "submissionDeadline": "2026-09-05T10:46:17.563Z",
      "winnerAnnouncement": "2026-09-16T11:46:17.563Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Rust Developers",
        "Solana Engineers",
        "Full-Stack Devs"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 5,
      "geography": "Global",
      "studentOnly": false,
      "prerequisites": "Must deploy on Solana Devnet or Mainnet-Beta."
    },
    "tracks": [
      {
        "id": "solana-track-depin",
        "title": "Track 1: DePIN & Consumer AI Apps on Solana",
        "prize": "$100,000 Grand Prize + $250k Colosseum Investment",
        "problemStatement": "Build mobile-friendly consumer apps utilizing Solana Mobile Stack, zero-friction compressed NFTs, or physical infrastructure telemetry.",
        "keyRequirements": [
          "Working Anchor program on Devnet",
          "Mobile-responsive web or Android APK"
        ],
        "evaluationCriteria": "35% Product Polish, 30% Smart Contract Security, 35% Tokenomics & Utility"
      }
    ],
    "judges": [
      {
        "name": "Anatoly Yakovenko",
        "role": "Co-Founder, Solana Labs",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Execution speed, high throughput, and consumer user experience."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repo with Anchor test suite",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Authored during hackathon."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Rust (Anchor Framework) + Next.js 15 + Solana Web3.js v2",
      "proTips": [
        "Make sure transaction confirmation takes under 1 second with optimistic UI updates."
      ]
    },
    "registrationUrl": "https://solana.com/hackathon",
    "submissionUrl": "https://colosseum.org"
  }
];
window.LIVE_TICKER_UPDATES = [
  {
    "tag": "DEVNOVATE",
    "text": "DevNovate 2026 ₹5 Lakh National Innovation Hackathon live on Radar!",
    "time": "Just Now"
  },
  {
    "tag": "UNSTOP",
    "text": "HackOn with Amazon 6.0 & IIT Guwahati InnovateX active on Unstop!",
    "time": "5m ago"
  },
  {
    "tag": "MICROSOFT",
    "text": "$100k Microsoft Imagine Cup 2026 registration open!",
    "time": "12m ago"
  },
  {
    "tag": "DORAHACKS",
    "text": "WEEX AI Wars II $200k grant pool accepting submissions!",
    "time": "20m ago"
  },
  {
    "tag": "SOLANA",
    "text": "Solana Renaissance $1M Global Hackathon ticking down!",
    "time": "30m ago"
  }
];
