// Automatically generated by Lily Deep-Research Engine at Sat, 05 Sep 2026 04:50:15 GMT
// Auto-syncs every 30 minutes in GitHub Cloud

window.HACKATHONS_DATA = [
  {
    "id": "devpost-google-agentic-cinema",
    "title": "Agentic Cinema: The Blockbuster Hackathon",
    "organizer": "Google Cloud & Gemini (with IBM, Grafana Labs, ClickHouse, Replit)",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    "bannerGradient": "from-blue-600 via-indigo-700 to-purple-950",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "Global Virtual (Devpost)",
    "totalPrizePool": 75000,
    "currency": "$",
    "featured": true,
    "tags": [
      "Google Cloud",
      "Gemini",
      "MCP",
      "AI Agents",
      "Media & VFX",
      "Devpost"
    ],
    "shortTeaser": "Build production-grade AI agents powered by Gemini Enterprise Agent Platform and Model Context Protocol (MCP) servers for media, cinematic production, and VFX workflows.",
    "timelines": {
      "registrationDeadline": "2026-09-12T04:50:15.339Z",
      "revealDate": "2026-08-24T04:50:15.339Z",
      "submissionDeadline": "2026-09-12T18:50:15.339Z",
      "winnerAnnouncement": "2026-09-23T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Developers",
        "AI Researchers",
        "Creative Technologists",
        "Indie Hackers"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "geography": "Global (except sanctioned jurisdictions)",
      "studentOnly": false,
      "prerequisites": "Must integrate Gemini models and at least one partner platform (IBM, Grafana, Parallel, ClickHouse, or Replit)."
    },
    "tracks": [
      {
        "id": "cinema-track-ibm",
        "title": "Track 1: IBM Enterprise Agent Governance & Orchestration",
        "prize": "$15,000 USD Track Pool (1st: $7.5k, 2nd: $4.5k, 3rd: $3k)",
        "problemStatement": "Architect multi-agent pipelines for cinematic script analysis, character continuity checking, and studio asset cataloging with strict governance guardrails.",
        "keyRequirements": [
          "Integrate Gemini 1.5/2.0 Pro with Model Context Protocol (MCP)",
          "Demonstrate automated multi-step agent reasoning and tracing",
          "Provide video demo showing live script parsing and structured JSON generation"
        ],
        "evaluationCriteria": "25% Technical Execution, 25% Gemini & Partner Integration, 25% Real-World Utility in Media, 25% Originality"
      },
      {
        "id": "cinema-track-clickhouse",
        "title": "Track 2: ClickHouse Real-Time High-Throughput Media Analytics",
        "prize": "$15,000 USD Track Pool",
        "problemStatement": "Build real-time vector and telemetry analytics pipelines over high-frequency video stream logs and automated AI dubbing subtitle generation.",
        "keyRequirements": [
          "Use ClickHouse for sub-second telemetry indexing",
          "Handle multimodal video/audio embeddings",
          "Deploy working prototype with interactive dashboard"
        ],
        "evaluationCriteria": "40% Query Performance, 30% Multimodal Architecture, 30% UI/UX Delight"
      }
    ],
    "judges": [
      {
        "name": "Google Cloud & Partner Panel",
        "role": "Principal AI Engineers & Solution Directors, Google Cloud & IBM",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Agentic autonomy, token efficiency, tool-calling resilience, and studio production viability."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with MIT/Apache license, architecture diagram, and setup README",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "All core software must be authored during the official hackathon period."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Next.js 15 + Google AI Studio Gemini SDK + Model Context Protocol (MCP) + ClickHouse Cloud",
      "proTips": [
        "Showcase seamless Model Context Protocol (MCP) tool-calling execution in your demo video without mock data.",
        "Highlight enterprise governance logs to maximize score on the IBM and Grafana judging criteria."
      ]
    },
    "registrationUrl": "https://agenticcinema.devpost.com",
    "submissionUrl": "https://agenticcinema.devpost.com"
  },
  {
    "id": "devpost-openai-webmcp",
    "title": "OpenAI WebMCP Challenge",
    "organizer": "OpenAI (with Google Chrome, Cloudflare, Vercel, Shopify, Netlify)",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg",
    "bannerGradient": "from-emerald-700 via-teal-800 to-slate-950",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "Global Virtual (Devpost)",
    "totalPrizePool": 35000,
    "currency": "$",
    "featured": true,
    "tags": [
      "OpenAI",
      "WebMCP",
      "Browser Agents",
      "Vercel",
      "Devpost",
      "Open to All"
    ],
    "shortTeaser": "Implement the Web Model Context Protocol (WebMCP) standard to enable browser-based AI agents to execute structured deterministic tool actions on live web apps.",
    "timelines": {
      "registrationDeadline": "2026-09-08T04:50:15.339Z",
      "revealDate": "2026-08-26T04:50:15.339Z",
      "submissionDeadline": "2026-09-08T17:50:15.339Z",
      "winnerAnnouncement": "2026-09-17T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Full-Stack Developers",
        "Frontend Engineers",
        "Browser Extension Authors"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "geography": "Worldwide",
      "studentOnly": false,
      "prerequisites": "Must implement WebMCP specification with live deployed web application."
    },
    "tracks": [
      {
        "id": "webmcp-track-1",
        "title": "Track 1: Dual-Interface Web Applications (Human UI + WebMCP Agent Tools)",
        "prize": "$30,000 Cash ($3,000 to Top 10 Teams) + Micro Codex Keyboards + 1-Year ChatGPT Pro",
        "problemStatement": "Transform existing web apps (e-commerce, SaaS, productivity) into agent-native systems where AI agents invoke direct schema-validated endpoints without visual screen scraping.",
        "keyRequirements": [
          "Implement WebMCP manifest and schema endpoints",
          "Provide human UI with real-time optimistic updates",
          "Include security authentication guardrails for agent actions"
        ],
        "evaluationCriteria": "35% WebMCP Spec Adherence, 25% User Security & Guardrails, 20% Real-World Utility, 20% UX"
      }
    ],
    "judges": [
      {
        "name": "OpenAI Developer Platform Team",
        "role": "Engineers & Product Leads, OpenAI & Vercel",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Protocol compliance, tool-calling determinism, and zero-latency agent handoffs."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repo with WebMCP manifest and live deployment URL",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": false,
      "codeFreshness": "Authored specifically for the WebMCP challenge."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Next.js 15 (App Router) + Vercel AI SDK + WebMCP Protocol Schema + Cloudflare Workers",
      "proTips": [
        "Demonstrate an AI agent completing a complex 5-step task (e.g. checkout, booking) with 100% precision."
      ]
    },
    "registrationUrl": "https://openai-webmcp.devpost.com",
    "submissionUrl": "https://openai-webmcp.devpost.com"
  },
  {
    "id": "solana-colosseum-fall-2026",
    "title": "Solana Colosseum Global Hackathon",
    "organizer": "Colosseum & Solana Foundation",
    "logo": "https://solana.com/favicon.ico",
    "bannerGradient": "from-fuchsia-600 via-purple-700 to-slate-900",
    "status": "upcoming",
    "statusLabel": "⏳ Registration Open",
    "mode": "Online",
    "location": "Global Virtual",
    "totalPrizePool": 350000,
    "currency": "$",
    "featured": true,
    "tags": [
      "Solana",
      "Colosseum",
      "DeFi",
      "DePIN",
      "Crypto x AI",
      "$250k Pre-Seed"
    ],
    "shortTeaser": "The flagship Solana ecosystem competition featuring $100k+ in direct USDC track prizes and guaranteed $250,000 USD pre-seed investments into Colosseum's accelerator program.",
    "timelines": {
      "registrationDeadline": "2026-10-03T04:50:15.339Z",
      "revealDate": "2026-09-25T04:50:15.339Z",
      "submissionDeadline": "2026-10-10T04:50:15.339Z",
      "winnerAnnouncement": "2026-10-25T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Rust Developers",
        "Solana Smart Contract Engineers",
        "Founders"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 5,
      "geography": "Global",
      "studentOnly": false,
      "prerequisites": "Must deploy on Solana Devnet or Mainnet-Beta with public GitHub repository."
    },
    "tracks": [
      {
        "id": "solana-track-ai-depin",
        "title": "Track 1: DePIN & On-Chain AI Agent Compute",
        "prize": "$50,000 Grand Prize + $250,000 Pre-Seed Accelerator Admission",
        "problemStatement": "Build verifiable compute coordination networks, decentralized telemetry oracles, and autonomous AI trading agents on Solana.",
        "keyRequirements": [
          "Anchor framework smart contracts",
          "Sub-400ms transaction confirmation",
          "Working frontend/mobile client"
        ],
        "evaluationCriteria": "35% Product-Market Fit, 30% Smart Contract Security, 35% Execution Speed & Tokenomics"
      }
    ],
    "judges": [
      {
        "name": "Anatoly Yakovenko & Colosseum Partners",
        "role": "Co-Founder, Solana Labs & Accelerator Directors",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Product execution, consumer utility, token velocity, and founder commitment."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repo with Anchor test suite and deployment scripts",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Developed for Colosseum hackathon cycle."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Rust (Anchor Framework) + Next.js 15 + Solana Web3.js v2 + Helius RPC",
      "proTips": [
        "Deploy on devnet early and include transaction signature links directly in your submission pitch deck."
      ]
    },
    "registrationUrl": "https://colosseum.org",
    "submissionUrl": "https://colosseum.org"
  },
  {
    "id": "unstop-iit-bbs-agentic-ai",
    "title": "IIT Bhubaneswar Agentic AI Hackathon (Tech Zephyr 4.0)",
    "organizer": "Indian Institute of Technology (IIT) Bhubaneswar & Unstop",
    "logo": "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/branding/unstop-logo.png",
    "bannerGradient": "from-cyan-700 via-blue-800 to-slate-950",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "Unstop Online & IIT Bhubaneswar Campus",
    "totalPrizePool": 35000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "Unstop",
      "IIT Bhubaneswar",
      "Agentic AI",
      "Multi-Agent",
      "Incubation"
    ],
    "shortTeaser": "Premier collegiate AI hackathon hosted by IIT Bhubaneswar on Unstop. Build autonomous multi-agent decision intelligence pipelines with tool use and local execution sandboxes.",
    "timelines": {
      "registrationDeadline": "2026-09-15T04:50:15.339Z",
      "revealDate": "2026-09-02T04:50:15.339Z",
      "submissionDeadline": "2026-09-15T22:50:15.339Z",
      "winnerAnnouncement": "2026-09-21T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Undergraduates",
        "Postgraduates",
        "Researchers",
        "Engineering Students"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "geography": "India & South Asia",
      "studentOnly": true,
      "prerequisites": "Must register on Unstop with verified college ID."
    },
    "tracks": [
      {
        "id": "iitbbs-track-agents",
        "title": "Track 1: Autonomous Multi-Agent Workflows & Tool Synthesis",
        "prize": "₹35,000 Cash Pool + Certificates & IIT Incubation Access",
        "problemStatement": "Develop multi-agent collaboration systems where agents independently plan, invoke custom tools, verify intermediate states, and resolve complex multi-step technical challenges.",
        "keyRequirements": [
          "Agent autonomy without continuous user prompts",
          "Modular tool-calling architecture",
          "Comprehensive test suite"
        ],
        "evaluationCriteria": "40% Agentic Autonomy, 30% Code Architecture, 30% Demo Presentation"
      }
    ],
    "judges": [
      {
        "name": "IIT Bhubaneswar Faculty & AI Mentors",
        "role": "Professors of Computer Science & AI Researchers",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Algorithmic soundness, multi-agent reasoning graphs, and latency optimization."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with system architecture README",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Original software created for Tech Zephyr 4.0."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Python LangGraph / CrewAI + FastAPI + React UI + Docker Sandbox",
      "proTips": [
        "Demonstrate multi-agent self-correction and rollback on unexpected tool outputs."
      ]
    },
    "registrationUrl": "https://unstop.com/hackathons",
    "submissionUrl": "https://unstop.com"
  },
  {
    "id": "unstop-iit-kgp-dataforge",
    "title": "DataForge 2026 (IIT Kharagpur - KDAG)",
    "organizer": "Kharagpur Data Analytics Group (KDAG), IIT Kharagpur & Unstop",
    "logo": "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/branding/unstop-logo.png",
    "bannerGradient": "from-blue-800 via-indigo-900 to-slate-950",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "Unstop Online & IIT Kharagpur",
    "totalPrizePool": 300000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "Unstop",
      "IIT Kharagpur",
      "Data Science",
      "Deep Learning",
      "Quant Finance"
    ],
    "shortTeaser": "Flagship competitive data science and machine learning competition on Unstop with ₹3 Lakh cash pool. Model high-dimensional unstructured datasets and quantitative financial networks.",
    "timelines": {
      "registrationDeadline": "2026-09-08T04:50:15.339Z",
      "revealDate": "2026-08-29T04:50:15.339Z",
      "submissionDeadline": "2026-09-09T03:50:15.339Z",
      "winnerAnnouncement": "2026-09-11T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Students",
        "Data Scientists",
        "Quant Enthusiasts"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 3,
      "geography": "India & Global",
      "studentOnly": true,
      "prerequisites": "Must register on Unstop."
    },
    "tracks": [
      {
        "id": "dataforge-track-ml",
        "title": "Track 1: Advanced Multimodal Predictive Modeling & Quant Anomaly Detection",
        "prize": "₹3,00,000 Cash Pool (1st: ₹1.5L, 2nd: ₹1.0L, 3rd: ₹50k)",
        "problemStatement": "Train state-of-the-art predictive architectures over massive real-world industrial and financial telemetry datasets to minimize false-positive rates under class imbalance.",
        "keyRequirements": [
          "Jupyter Notebook / Python script with clean pipeline",
          "Documented cross-validation methodology",
          "Final predictions CSV"
        ],
        "evaluationCriteria": "40% Private Leaderboard Metric (ROC-AUC/F1), 30% Feature Engineering, 30% Methodology Quality"
      }
    ],
    "judges": [
      {
        "name": "KDAG & Industry Quant Jury",
        "role": "Data Science Leaders & Alumni",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Model generalizability, leakage prevention, and mathematical justification."
      }
    ],
    "rules": {
      "repoRequirement": "Reproducible code repository with requirements.txt and model checkpoints",
      "demoVideoMaxSecs": 120,
      "liveUrlRequired": false,
      "slideDeckRequired": true,
      "codeFreshness": "Original code authored for DataForge 2026."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Python PyTorch + LightGBM + Polars + Scikit-Learn + Optuna Hyperparameter Tuning",
      "proTips": [
        "Focus heavily on domain-specific feature engineering rather than just ensembling raw models."
      ]
    },
    "registrationUrl": "https://unstop.com/hackathons",
    "submissionUrl": "https://unstop.com"
  },
  {
    "id": "devnovate-2026",
    "title": "DevNovate 2026 National Innovation Hackathon",
    "organizer": "DevNovate Foundation & Devfolio",
    "logo": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80",
    "bannerGradient": "from-indigo-600 via-purple-700 to-slate-950",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "Devfolio Virtual & Bangalore Hub",
    "totalPrizePool": 500000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "DevNovate",
      "Devfolio",
      "AI/ML",
      "FinTech",
      "HealthTech",
      "Web3"
    ],
    "shortTeaser": "Flagship national innovation hackathon bringing together 5,000+ developers to build transformative AI agents, next-gen decentralized finance, and public health software.",
    "timelines": {
      "registrationDeadline": "2026-09-13T04:50:15.339Z",
      "revealDate": "2026-09-01T04:50:15.339Z",
      "submissionDeadline": "2026-09-11T16:50:15.339Z",
      "winnerAnnouncement": "2026-09-21T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "Developers",
        "Designers",
        "Students",
        "Founders"
      ],
      "teamSizeMin": 2,
      "teamSizeMax": 4,
      "geography": "Open to All Developers Globally & India",
      "studentOnly": false,
      "prerequisites": "Must register on DevNovate portal with public GitHub profile."
    },
    "tracks": [
      {
        "id": "devnovate-track-ai",
        "title": "Track 1: Agentic AI & Autonomous Developer Tooling",
        "prize": "₹2,00,000 Cash + Cloud Infrastructure Grants",
        "problemStatement": "Build autonomous multi-agent pipelines that understand codebase repositories, automate bug fixes, and generate verified test suites with zero hallucination.",
        "keyRequirements": [
          "Integrate LLM tool calling (Gemini, Claude, or OpenAI)",
          "Provide real-time execution sandboxing (WebAssembly or Docker)",
          "Demonstrate automated git commit & PR creation"
        ],
        "evaluationCriteria": "35% Autonomous Accuracy, 30% Architecture & Speed, 20% UI/UX, 15% Pitch Demo"
      }
    ],
    "judges": [
      {
        "name": "Saurabh Sharma",
        "role": "VP of Engineering, DevNovate & Cloud Architect",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Distributed systems, agentic workflow orchestration, and low-latency API design."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with MIT/Apache license and comprehensive README documentation",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "All submitted code and models must be developed within the hackathon timeline."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Next.js 15 (App Router) + FastAPI (Python) + PostgreSQL / Pinecone + Vercel Deployment",
      "proTips": [
        "Include a clear 1-minute video showing the agent executing end-to-end without cuts."
      ]
    },
    "registrationUrl": "https://devfolio.co/hackathons",
    "submissionUrl": "https://devfolio.co"
  },
  {
    "id": "unstop-amazon-hackon-6",
    "title": "HackOn with Amazon 6.0",
    "organizer": "Amazon & Unstop",
    "logo": "https://d8it4huxumps7.cloudfront.net/uploads/images/unstop/user-images/6571520626359_amazon.svg",
    "bannerGradient": "from-amber-600 via-orange-700 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Online",
    "location": "Unstop Virtual & India",
    "totalPrizePool": 225000,
    "currency": "₹",
    "featured": true,
    "tags": [
      "Unstop",
      "Amazon",
      "Software Dev",
      "PPI Opportunities",
      "Engineering"
    ],
    "shortTeaser": "Amazon's flagship student hackathon on Unstop. Solve real e-commerce, cloud, and AI engineering challenges for cash prizes & Pre-Placement Interviews (PPIs).",
    "timelines": {
      "registrationDeadline": "2026-09-15T04:50:15.339Z",
      "revealDate": "2026-08-31T04:50:15.339Z",
      "submissionDeadline": "2026-09-13T22:50:15.339Z",
      "winnerAnnouncement": "2026-09-25T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 18,
      "allowedRoles": [
        "B.Tech/B.E.",
        "M.Tech",
        "MCA Students"
      ],
      "teamSizeMin": 2,
      "teamSizeMax": 4,
      "geography": "India & South Asia Engineering Students",
      "studentOnly": true,
      "prerequisites": "Must register through Unstop platform."
    },
    "tracks": [
      {
        "id": "amazon-track-1",
        "title": "Track 1: High-Scale E-Commerce & AI Customer Experience",
        "prize": "₹2,25,000 + Amazon Pre-Placement Interviews (PPI)",
        "problemStatement": "Architect a resilient, fault-tolerant microservice that predicts inventory demand spikes and handles 100,000 requests/sec during festive sales.",
        "keyRequirements": [
          "Use Java, Python, or Go for core backend logic",
          "Include architectural system design diagram",
          "Demonstrate load testing results"
        ],
        "evaluationCriteria": "40% System Scalability, 30% Code Architecture, 30% Prototype Demo"
      }
    ],
    "judges": [
      {
        "name": "Amazon Tech Leaders",
        "role": "Principal Software Engineers, Amazon",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Distributed systems, low latency, and operational excellence."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with system architecture documentation",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Authored specifically for HackOn with Amazon 6.0."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Java Spring Boot / Python FastAPI + AWS DynamoDB + Docker + React",
      "proTips": [
        "Include load testing benchmarks (JMeter / K6) in your submission deck to impress Amazon judges."
      ]
    },
    "registrationUrl": "https://unstop.com/hackathons/hackon-with-amazon-60-amazon-1150000",
    "submissionUrl": "https://unstop.com"
  },
  {
    "id": "microsoft-imagine-cup-2026",
    "title": "Microsoft Imagine Cup 2026",
    "organizer": "Microsoft",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    "bannerGradient": "from-sky-700 via-blue-800 to-slate-900",
    "status": "live",
    "statusLabel": "🔥 Live Submissions Open",
    "mode": "Hybrid",
    "location": "Global Online & Seattle Finals",
    "totalPrizePool": 100000,
    "currency": "$",
    "featured": true,
    "tags": [
      "Microsoft",
      "Azure AI",
      "Student Founder",
      "$100k Prize",
      "Global"
    ],
    "shortTeaser": "The premier global student technology competition. Build an AI-driven startup on Microsoft Azure for $100,000 USD, mentorship from Satya Nadella, and global recognition.",
    "timelines": {
      "registrationDeadline": "2026-09-25T04:50:15.339Z",
      "revealDate": "2026-08-21T04:50:15.339Z",
      "submissionDeadline": "2026-09-20T18:50:15.339Z",
      "winnerAnnouncement": "2026-10-20T04:50:15.339Z"
    },
    "eligibility": {
      "minAge": 16,
      "allowedRoles": [
        "Students (High School, Undergrad, Grad)"
      ],
      "teamSizeMin": 1,
      "teamSizeMax": 4,
      "geography": "Worldwide",
      "studentOnly": true,
      "prerequisites": "Must utilize Microsoft Azure AI or OpenAI on Azure."
    },
    "tracks": [
      {
        "id": "imagine-track-1",
        "title": "Track 1: AI-Powered Global Impact Ventures",
        "prize": "$100,000 USD + Mentorship with Satya Nadella",
        "problemStatement": "Build an MVP leveraging Azure OpenAI, Computer Vision, or Speech services to address accessibility, sustainability, education, or healthcare inequities.",
        "keyRequirements": [
          "Working proof-of-concept deployed on Azure",
          "3-minute pitch video explaining commercial viability",
          "Architecture system documentation"
        ],
        "evaluationCriteria": "30% Innovation & AI Integration, 25% Business Model, 25% User Experience, 20% Pitch Quality"
      }
    ],
    "judges": [
      {
        "name": "Microsoft Executive Panel",
        "role": "Microsoft Corporate VPs & Fellows",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        "focusArea": "Scalability, ethics in AI, and global market potential."
      }
    ],
    "rules": {
      "repoRequirement": "Public GitHub repository with architecture diagram",
      "demoVideoMaxSecs": 180,
      "liveUrlRequired": true,
      "slideDeckRequired": true,
      "codeFreshness": "Authored for Imagine Cup 2026 cycle."
    },
    "winningPlaybook": {
      "techStackRecommendation": "Azure Container Apps + Next.js + Azure OpenAI GPT-4o + CosmosDB",
      "proTips": [
        "Emphasize how your solution can turn into a venture-backed startup."
      ]
    },
    "registrationUrl": "https://imaginecup.microsoft.com",
    "submissionUrl": "https://imaginecup.microsoft.com"
  }
];
window.LIVE_TICKER_UPDATES = [
  {
    "tag": "DEVPOST",
    "text": "Google Agentic Cinema $75k & OpenAI WebMCP $35k live on Devpost!",
    "time": "Just Now"
  },
  {
    "tag": "UNSTOP",
    "text": "IIT Bhubaneswar Agentic AI & IIT Kharagpur DataForge active on Unstop!",
    "time": "4m ago"
  },
  {
    "tag": "SOLANA",
    "text": "Colosseum Fall $350k Solana Global Hackathon registration open!",
    "time": "10m ago"
  },
  {
    "tag": "DEVNOVATE",
    "text": "DevNovate 2026 ₹5 Lakh Innovation Hackathon live on Devfolio!",
    "time": "18m ago"
  },
  {
    "tag": "MICROSOFT",
    "text": "Microsoft Imagine Cup $100k + Satya Nadella mentorship cycle open!",
    "time": "25m ago"
  }
];
